# Generated by Django 2.0.1 on 2018-03-24 07:36

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUsersA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Allowed Users in Mega A',
            },
        ),
        migrations.CreateModel(
            name='AllowedUsersB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Allowed Users in Mega B',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=11)),
                ('comment_dept', models.CharField(default='', max_length=100)),
                ('comment_user', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2018, 3, 24, 15, 36, 34, 15925))),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='MegaA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo_date', models.DateField(default=datetime.date(2018, 3, 24))),
                ('jo_no', models.CharField(max_length=200)),
                ('jo_code', models.CharField(max_length=200)),
                ('jo_clients', models.CharField(max_length=200)),
                ('study', models.TextField(default='Study..', max_length=300)),
                ('jo_qlqnChoices', multiselectfield.db.fields.MultiSelectField(choices=[('QL', 'QL'), ('QN', 'QN')], max_length=5)),
                ('jo_project_no', models.CharField(max_length=200)),
                ('jo_contact_price', models.CharField(max_length=200)),
                ('jo_terms', models.CharField(max_length=200)),
                ('jo_vat', models.CharField(max_length=200)),
                ('jo_sign_contract', models.CharField(max_length=100)),
                ('jo_po_no', models.CharField(max_length=200)),
                ('jo_pcr_recieve', models.DateField(blank=True, default=None, null=True)),
                ('jo_pcr_date_bill', models.DateField(blank=True, default=None, null=True)),
                ('jo_pcr_invoice', models.CharField(max_length=200)),
                ('jo_pcr_or', models.CharField(max_length=200)),
                ('jo_pcr_payment_date', models.DateField(blank=True, default=None, null=True)),
                ('jo_coc', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date1', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice1', models.CharField(default='0', max_length=200)),
                ('jo_or1', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_1', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date2', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice2', models.CharField(default='0', max_length=200)),
                ('jo_or2', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_2', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date3', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice3', models.CharField(default='0', max_length=200)),
                ('jo_or3', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_3', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date4', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice4', models.CharField(default='0', max_length=200)),
                ('jo_or4', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_4', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date5', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice5', models.CharField(default='0', max_length=200)),
                ('jo_or5', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_5', models.DateField(blank=True, default=None, null=True)),
                ('jo_addendum_date', models.DateField(blank=True, default=None, null=True)),
                ('jo_addendum', models.CharField(default='0', max_length=100)),
                ('jo_remarks', models.CharField(max_length=200)),
                ('jo_rev', models.IntegerField(default='0', max_length=11)),
            ],
            options={
                'verbose_name_plural': 'MegaA - Projects',
            },
        ),
        migrations.CreateModel(
            name='MegaB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo_date', models.DateField(default=datetime.date(2018, 3, 24))),
                ('jo_no', models.CharField(max_length=200)),
                ('jo_code', models.CharField(max_length=200)),
                ('jo_clients', models.CharField(max_length=200)),
                ('study', models.TextField(default='Study..', max_length=300)),
                ('jo_qlqnChoices', multiselectfield.db.fields.MultiSelectField(choices=[('QL', 'QL'), ('QN', 'QN')], max_length=5)),
                ('jo_project_no', models.CharField(max_length=200)),
                ('jo_contact_price', models.CharField(max_length=200)),
                ('jo_terms', models.CharField(max_length=200)),
                ('jo_vat', models.CharField(max_length=200)),
                ('jo_sign_contract', models.CharField(max_length=100)),
                ('jo_po_no', models.CharField(max_length=200)),
                ('jo_pcr_recieve', models.DateField(blank=True, default=None, null=True)),
                ('jo_pcr_date_bill', models.DateField(blank=True, default=None, null=True)),
                ('jo_pcr_invoice', models.CharField(max_length=200)),
                ('jo_pcr_or', models.CharField(max_length=200)),
                ('jo_pcr_payment_date', models.DateField(blank=True, default=None, null=True)),
                ('jo_coc', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date1', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice1', models.CharField(default='0', max_length=200)),
                ('jo_or1', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_1', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date2', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice2', models.CharField(default='0', max_length=200)),
                ('jo_or2', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_2', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date3', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice3', models.CharField(default='0', max_length=200)),
                ('jo_or3', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_3', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date4', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice4', models.CharField(default='0', max_length=200)),
                ('jo_or4', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_4', models.DateField(blank=True, default=None, null=True)),
                ('jo_inv_date5', models.DateField(blank=True, default=None, null=True)),
                ('jo_invoice5', models.CharField(default='0', max_length=200)),
                ('jo_or5', models.CharField(default='0', max_length=200)),
                ('jo_payment_date_5', models.DateField(blank=True, default=None, null=True)),
                ('jo_addendum_date', models.DateField(blank=True, default=None, null=True)),
                ('jo_addendum', models.CharField(default='0', max_length=100)),
                ('jo_remarks', models.CharField(max_length=200)),
                ('jo_rev', models.IntegerField(default='0', max_length=11)),
            ],
            options={
                'verbose_name_plural': 'MegaB - Projects',
            },
        ),
    ]
