# Generated by Django 2.0.1 on 2018-02-24 02:39

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=11)),
                ('comment_user', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2018, 2, 24, 10, 39, 58, 416170))),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Job_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo_date', models.DateField(default=datetime.date(2018, 2, 24))),
                ('jo_no', models.CharField(max_length=200)),
                ('jo_code', models.CharField(max_length=200)),
                ('jo_study', models.TextField(max_length=500)),
                ('jo_clients', models.CharField(max_length=200)),
                ('jo_qlqnChoices', multiselectfield.db.fields.MultiSelectField(choices=[('QL', 'QL'), ('QN', 'QN')], max_length=5)),
                ('jo_project_no', models.CharField(max_length=200)),
                ('jo_contact_price', models.CharField(max_length=200)),
                ('jo_terms', models.CharField(max_length=200)),
                ('jo_vat', models.CharField(max_length=200)),
                ('jo_sign_contract', models.CharField(max_length=100)),
                ('jo_po_no', models.CharField(max_length=200)),
                ('jo_pcr', models.CharField(max_length=200)),
                ('jo_coc', multiselectfield.db.fields.MultiSelectField(choices=[('nococ', 'nococ'), ('coc', 'coc')], default='nococ', max_length=9)),
                ('jo_inv_no', models.CharField(max_length=100)),
                ('jo_or_date', models.DateField(default=datetime.date(2018, 2, 24))),
                ('jo_second_inv', models.CharField(max_length=100)),
                ('jo_payment_date1', models.DateField(default=datetime.date(2018, 2, 24))),
                ('jo_final_billing', models.CharField(max_length=100)),
                ('jo_payment_date2', models.DateField(default=datetime.date(2018, 2, 24))),
                ('jo_remarks', models.CharField(max_length=200)),
                ('jo_revisions', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
