# Generated by Django 2.0.1 on 2018-03-19 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0002_auto_20180317_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaa',
            name='jo_addendum_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_final_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_addendum_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_final_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 16, 2, 16, 653559)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date1',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date10',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date11',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date12',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date13',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date2',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date3',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date4',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date5',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date6',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date7',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date8',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date9',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_or_date',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_payment_date1',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_payment_date2',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date1',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date10',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date11',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date12',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date13',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date2',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date3',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date4',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date5',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date6',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date7',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date8',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date9',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_or_date',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_payment_date1',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_payment_date2',
            field=models.DateField(default=datetime.date(2018, 3, 19)),
        ),
    ]
