# Generated by Django 2.0.1 on 2018-02-24 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0003_auto_20180224_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_table',
            name='jo_revisions',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 10, 43, 22, 561376)),
        ),
    ]
