# Generated by Django 2.0.1 on 2018-02-24 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0004_auto_20180224_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_table',
            name='study',
            field=models.TextField(default='Study..', max_length=300),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 10, 44, 26, 612382)),
        ),
    ]
