# Generated by Django 2.0.1 on 2018-03-24 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0005_auto_20180324_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 24, 16, 49, 20, 879427)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_remarks',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_remarks',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
