# Generated by Django 2.0.1 on 2018-02-24 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0005_auto_20180224_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 10, 45, 44, 255917)),
        ),
    ]
