# Generated by Django 2.0.1 on 2018-03-22 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0006_auto_20180320_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 22, 20, 2, 49, 42158)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 3, 22)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date1',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date3',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date4',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_inv_date5',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_or_date',
            field=models.DateField(default=datetime.date(2018, 3, 22)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_payment_date1',
            field=models.DateField(default=datetime.date(2018, 3, 22)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_payment_date2',
            field=models.DateField(default=datetime.date(2018, 3, 22)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 3, 22)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date1',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date3',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date4',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_inv_date5',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_or_date',
            field=models.DateField(default=datetime.date(2018, 3, 22)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_payment_date1',
            field=models.DateField(default=datetime.date(2018, 3, 22)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_payment_date2',
            field=models.DateField(default=datetime.date(2018, 3, 22)),
        ),
    ]
