# Generated by Django 2.0.1 on 2018-03-23 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0007_auto_20180322_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megaa',
            name='jo_inv_no',
        ),
        migrations.RemoveField(
            model_name='megaa',
            name='jo_or_date',
        ),
        migrations.RemoveField(
            model_name='megaa',
            name='jo_payment_date1',
        ),
        migrations.RemoveField(
            model_name='megaa',
            name='jo_payment_date2',
        ),
        migrations.RemoveField(
            model_name='megaa',
            name='jo_second_inv',
        ),
        migrations.RemoveField(
            model_name='megab',
            name='jo_inv_no',
        ),
        migrations.RemoveField(
            model_name='megab',
            name='jo_or_date',
        ),
        migrations.RemoveField(
            model_name='megab',
            name='jo_payment_date1',
        ),
        migrations.RemoveField(
            model_name='megab',
            name='jo_payment_date2',
        ),
        migrations.RemoveField(
            model_name='megab',
            name='jo_second_inv',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 15, 13, 28, 700531)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 3, 23)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 3, 23)),
        ),
    ]
