# Generated by Django 2.0.1 on 2018-02-24 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0010_auto_20180224_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_table',
            old_name='jo_attendum',
            new_name='jo_addendum',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 11, 50, 5, 898238)),
        ),
    ]
