# Generated by Django 2.0.1 on 2018-02-24 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0013_auto_20180224_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 13, 48, 53, 642265)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_dept',
            field=models.CharField(default='', max_length=100),
        ),
    ]
