# Generated by Django 2.0.1 on 2018-02-24 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0014_auto_20180224_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaa',
            name='allowed_users',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='megab',
            name='allowed_users',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 14, 53, 55, 972626)),
        ),
    ]
