# Generated by Django 2.0.1 on 2018-02-24 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0015_auto_20180224_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megaa',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='megab',
            name='allowed_users',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 14, 56, 4, 365362)),
        ),
    ]
