# Generated by Django 2.0.1 on 2018-02-24 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0017_auto_20180224_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUsersA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedUsersB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 15, 0, 33, 342108)),
        ),
    ]
