# Generated by Django 2.0.1 on 2018-02-24 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0018_auto_20180224_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedusersa',
            options={'verbose_name_plural': 'Allowed Users in Mega A'},
        ),
        migrations.AlterModelOptions(
            name='allowedusersb',
            options={'verbose_name_plural': 'Allowed Users in Mega B'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 24, 15, 4, 25, 194604)),
        ),
    ]
