# Generated by Django 2.0.1 on 2018-02-28 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0019_auto_20180224_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaa',
            name='jo_or',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 16, 53, 45, 761701)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_or_date',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_payment_date1',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_payment_date2',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_or_date',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_payment_date1',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_payment_date2',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
    ]
