# Generated by Django 2.0.1 on 2018-03-09 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0020_auto_20180228_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='megaa',
            name='jo_rev',
            field=models.IntegerField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_rev',
            field=models.IntegerField(default='0', max_length=11),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 16, 2, 18, 734127)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 3, 9)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_or_date',
            field=models.DateField(default=datetime.date(2018, 3, 9)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_payment_date1',
            field=models.DateField(default=datetime.date(2018, 3, 9)),
        ),
        migrations.AlterField(
            model_name='megaa',
            name='jo_payment_date2',
            field=models.DateField(default=datetime.date(2018, 3, 9)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_date',
            field=models.DateField(default=datetime.date(2018, 3, 9)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_or_date',
            field=models.DateField(default=datetime.date(2018, 3, 9)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_payment_date1',
            field=models.DateField(default=datetime.date(2018, 3, 9)),
        ),
        migrations.AlterField(
            model_name='megab',
            name='jo_payment_date2',
            field=models.DateField(default=datetime.date(2018, 3, 9)),
        ),
    ]
