# Generated by Django 2.0.1 on 2018-03-09 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0021_auto_20180309_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megaa',
            name='jo_or',
        ),
        migrations.RemoveField(
            model_name='megab',
            name='jo_or',
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice10',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice11',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice12',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice13',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice3',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice4',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice5',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice6',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice7',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice8',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_invoice9',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or10',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or11',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or12',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or13',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or3',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or4',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or5',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or6',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or7',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or8',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megaa',
            name='jo_or9',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice10',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice11',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice12',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice13',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice3',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice4',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice5',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice6',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice7',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice8',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_invoice9',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or1',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or10',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or11',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or12',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or13',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or3',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or4',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or5',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or6',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or7',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or8',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='megab',
            name='jo_or9',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 16, 7, 43, 26558)),
        ),
    ]
