# Generated by Django 2.0.1 on 2018-03-09 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_order_sys', '0022_auto_20180309_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 17, 55, 7, 448250)),
        ),
    ]
